### ISSUE TITLE
Initialise Algorithm Nodes

### ISSUE THREAD

**Issue by luciansargeant** [bawalsh/hackslash#72]
Currently the nodes aren't being created.

**Comment by kmdinake** [comment]
@luciansargeant Are you referring to the algorithm nodes that should be created in the init_algorithm_nodes.py file? Does the Dockerfile that you have locally contain the following line: python3 init_algorithm_nodes.py; ?
If it does not then that is the cause of the algorithm nodes not being created. 

Are there any detailed errors that appear when you run the docker?
